export const inplayEvents = [
  {
    openDate: "2025-11-21T01:00:00.000+00:00",
    customOpenDate: "2025-11-21T02:30:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "RX123",
    competitionName: "Other",
    eventId: "1763500008",
    customEventName: "THE ASHES 2025 - 2026",
    eventName: "The Ashes 2025-2026 v .",
    status: "IN_PLAY",
    providerName: "RX",
    markets: {
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: true,
    favoritePriority: 3,
  },
  {
    openDate: "2026-01-05T23:00:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "12195619",
    competitionName: "Australia NCL Women",
    eventId: "35111060",
    eventName: "Tasmania W v Queensland Fire W",
    marketId: "1.252343296",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252343296",
          marketName: "Match Odds",
          marketTime: 1767654000000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "89039413",
              runnerName: "Tasmania W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 12,
                  size: 3.8,
                },
              ],
              layPrices: [
                {
                  price: 18,
                  size: 2.33,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "88983850",
              runnerName: "Queensland Fire W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.06,
                  size: 39.58,
                },
              ],
              layPrices: [
                {
                  price: 1.09,
                  size: 41.9,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "7104",
  },
  {
    openDate: "2026-01-05T23:00:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "12195619",
    competitionName: "Australia NCL Women",
    eventId: "35100569",
    eventName: "ACT Meteors W v Victoria W",
    marketId: "1.252242997",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252242997",
          marketName: "Match Odds",
          marketTime: 1767654000000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "89681313",
              runnerName: "ACT Meteors W",
              status: "ACTIVE",
              layPrices: [
                {
                  price: 1.01,
                  size: 6948.54,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "77707498",
              runnerName: "Victoria W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1000,
                  size: 29.43,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "7109",
  },
  {
    openDate: "2026-01-05T23:01:00.000+00:00",
    customOpenDate: "2026-01-03T23:30:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "12444379",
    competitionName: "The Ashes",
    eventId: "35094251",
    eventName: "Australia v England",
    marketId: "1.252151159",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252151159",
          marketName: "Match Odds",
          marketTime: 1767654060000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "16606",
              runnerName: "Australia",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.31,
                  size: 2220.96,
                },
              ],
              layPrices: [
                {
                  price: 1.32,
                  size: 6381.78,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "10301",
              runnerName: "England",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 13.5,
                  size: 1289.43,
                },
              ],
              layPrices: [
                {
                  price: 14,
                  size: 386.46,
                },
              ],
              sort: "2",
            },
            {
              runnerId: "60443",
              runnerName: "The Draw",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 6,
                  size: 1227.95,
                },
              ],
              layPrices: [
                {
                  price: 6.2,
                  size: 469.27,
                },
              ],
              sort: "3",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: true,
    favoritePriority: 2,
    liveStreamChannelId: "7106",
  },
  {
    openDate: "2026-01-06T03:30:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "10957170",
    competitionName: "Vijay Hazare Trophy",
    eventId: "35111981",
    eventName: "Kerala v Puducherry",
    marketId: "1.252318144",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252318144",
          marketName: "Match Odds",
          marketTime: 1767670200000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "8174933",
              runnerName: "Kerala",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.24,
                  size: 145.8,
                },
              ],
              layPrices: [
                {
                  price: 1.38,
                  size: 1.35,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "20714847",
              runnerName: "Puducherry",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.55,
                  size: 1.72,
                },
              ],
              layPrices: [
                {
                  price: 5.1,
                  size: 1.08,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "7105",
  },
  {
    openDate: "2026-01-06T03:50:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "12162210",
    competitionName: "Womens Super Smash T20",
    eventId: "35114992",
    eventName: "Auckland Hearts W v Otago Sparks W",
    marketId: "1.252377909",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252377909",
          marketName: "Match Odds",
          marketTime: 1767671400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "91002048",
              runnerName: "Auckland Hearts W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.77,
                  size: 40.96,
                },
              ],
              layPrices: [
                {
                  price: 1.8,
                  size: 673.55,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "91002047",
              runnerName: "Otago Sparks W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.24,
                  size: 541.25,
                },
              ],
              layPrices: [
                {
                  price: 2.3,
                  size: 32.39,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "7101",
  },
  {
    openDate: "2026-01-06T03:50:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "RX123",
    competitionName: "Other",
    eventId: "1767570042",
    eventName: "NEW ZEALAND T10 v SOUTH AFRICA T10",
    status: "IN_PLAY",
    providerName: "RX",
    markets: {
      enableMatchOdds: false,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: true,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:30:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "RX123",
    competitionName: "Other",
    eventId: "1767599254",
    eventName: "MUMBAI INDIANS SUPER OVER v PUNJAB KINGS SUPER OVER",
    status: "IN_PLAY",
    providerName: "RX",
    markets: {
      enableMatchOdds: false,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: true,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:40:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "RX123",
    competitionName: "Other",
    eventId: "1767570057",
    eventName: "AUSTRALIA T10 v ENGLAND T10",
    status: "IN_PLAY",
    providerName: "RX",
    markets: {
      enableMatchOdds: false,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: true,
    favorite: false,
  },

  {
    openDate: "2026-01-06T02:09:56.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12546216",
    competitionName: "United Cup",
    eventId: "35105190",
    eventName: "Flavio Cobolli v Arthur Rinderknech",
    marketId: "1.252259963",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252259963",
          marketName: "Match Odds",
          marketTime: 1767665396000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "16570658",
              runnerName: "Flavio Cobolli",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.45,
                  size: 28.05,
                },
              ],
              layPrices: [
                {
                  price: 1.46,
                  size: 221.96,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "9953233",
              runnerName: "Arthur Rinderknech",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.15,
                  size: 102.88,
                },
              ],
              layPrices: [
                {
                  price: 3.25,
                  size: 12.52,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "493",
  },
  {
    openDate: "2026-01-06T03:00:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776599",
    competitionName: "Nonthaburi Challenger 2026",
    eventId: "35112030",
    eventName: "S Fomin v Tokuda",
    marketId: "1.252318025",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252318025",
          marketName: "Match Odds",
          marketTime: 1767668400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "11102188",
              runnerName: "Sergey Fomin",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.06,
                  size: 99.16,
                },
              ],
              layPrices: [
                {
                  price: 2.14,
                  size: 121.35,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "9629509",
              runnerName: "Renta Tokuda",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.89,
                  size: 44.87,
                },
              ],
              layPrices: [
                {
                  price: 1.94,
                  size: 85.13,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "503",
  },
  {
    openDate: "2026-01-06T03:00:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776429",
    competitionName: "ATP Brisbane 2026",
    eventId: "35110565",
    eventName: "Mpetshi Perricard v Paul",
    marketId: "1.252302523",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252302523",
          marketName: "Match Odds",
          marketTime: 1767668400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "19544747",
              runnerName: "Giovanni Mpetshi Perricard",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.72,
                  size: 127.97,
                },
              ],
              layPrices: [
                {
                  price: 2.78,
                  size: 1.01,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "8859306",
              runnerName: "Tommy Paul",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.56,
                  size: 910.63,
                },
              ],
              layPrices: [
                {
                  price: 1.58,
                  size: 220.3,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: true,
    liveStreamChannelId: "254",
  },
  {
    openDate: "2026-01-06T03:00:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776599",
    competitionName: "Nonthaburi Challenger 2026",
    eventId: "35111985",
    eventName: "Ro Pacheco Mendez v R Bertrand",
    marketId: "1.252317844",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252317844",
          marketName: "Match Odds",
          marketTime: 1767668400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "38618554",
              runnerName: "Rodrigo Pacheco Mendez",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.83,
                  size: 272.64,
                },
              ],
              layPrices: [
                {
                  price: 1.88,
                  size: 1.85,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "27997038",
              runnerName: "Robin Bertrand",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.12,
                  size: 290.81,
                },
              ],
              layPrices: [
                {
                  price: 2.2,
                  size: 16.72,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "505",
  },
  {
    openDate: "2026-01-06T03:05:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776545",
    competitionName: "Canberra Challenger 2026",
    eventId: "35117799",
    eventName: "Jodar v Jarry",
    marketId: "1.252383834",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252383834",
          marketName: "Match Odds",
          marketTime: 1767668700000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "51053591",
              runnerName: "Rafael Jodar",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.21,
                  size: 699.25,
                },
              ],
              layPrices: [
                {
                  price: 1.27,
                  size: 769.03,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "8260515",
              runnerName: "Nicolas Jarry",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 4.7,
                  size: 209.78,
                },
              ],
              layPrices: [
                {
                  price: 5.7,
                  size: 76.26,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "298",
  },

  {
    openDate: "2026-01-06T03:50:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776545",
    competitionName: "Canberra Challenger 2026",
    eventId: "35117819",
    eventName: "Cassone v L Klein",
    marketId: "1.252384138",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252384138",
          marketName: "Match Odds",
          marketTime: 1767671400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "26794136",
              runnerName: "Murphy Cassone",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.34,
                  size: 23.77,
                },
              ],
              layPrices: [
                {
                  price: 1.35,
                  size: 355.96,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "9635456",
              runnerName: "Lukas Klein",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.85,
                  size: 197.95,
                },
              ],
              layPrices: [
                {
                  price: 3.95,
                  size: 8.06,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "300",
  },
  {
    openDate: "2026-01-06T03:50:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776378",
    competitionName: "WTA Auckland 2026",
    eventId: "35110373",
    eventName: "Aly Parks v El Cocciaretto",
    marketId: "1.252298505",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252298505",
          marketName: "Match Odds",
          marketTime: 1767671400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "11233227",
              runnerName: "Alycia Parks",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 12,
                  size: 796.55,
                },
              ],
              layPrices: [
                {
                  price: 12.5,
                  size: 1.17,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "18848114",
              runnerName: "Elisabetta Cocciaretto",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.08,
                  size: 822.36,
                },
              ],
              layPrices: [
                {
                  price: 1.09,
                  size: 8769.32,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "491",
  },
  {
    openDate: "2026-01-06T04:00:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776647",
    competitionName: "WTA Canberra 2026",
    eventId: "35111146",
    eventName: "Stakusic v Dar Vidmanova",
    marketId: "1.252306617",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252306617",
          marketName: "Match Odds",
          marketTime: 1767672000000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "24918570",
              runnerName: "Marina Stakusic",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.62,
                  size: 151.83,
                },
              ],
              layPrices: [
                {
                  price: 3.4,
                  size: 50.92,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "20832525",
              runnerName: "Darja Vidmanova",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.42,
                  size: 2.91,
                },
              ],
              layPrices: [
                {
                  price: 1.61,
                  size: 2.3,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "501",
  },

  {
    openDate: "2026-01-06T04:10:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776545",
    competitionName: "Canberra Challenger 2026",
    eventId: "35117794",
    eventName: "Ch Rodesch v Lu Nardi",
    marketId: "1.252383759",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252383759",
          marketName: "Match Odds",
          marketTime: 1767672600000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "20240210",
              runnerName: "Chris Rodesch",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.78,
                  size: 2.04,
                },
              ],
              layPrices: [
                {
                  price: 1.88,
                  size: 132.56,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "19544753",
              runnerName: "Luca Nardi",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.14,
                  size: 116.45,
                },
              ],
              layPrices: [
                {
                  price: 2.3,
                  size: 124.45,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "305",
  },
  {
    openDate: "2026-01-06T04:10:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776346",
    competitionName: "WTA Brisbane 2026",
    eventId: "35114711",
    eventName: "Sof Kenin v Alexandrova",
    marketId: "1.252342828",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252342828",
          marketName: "Match Odds",
          marketTime: 1767672600000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "9149629",
              runnerName: "Sofia Kenin",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 7.2,
                  size: 17.11,
                },
              ],
              layPrices: [
                {
                  price: 7.8,
                  size: 227.3,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "8681458",
              runnerName: "Ekaterina Alexandrova",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.15,
                  size: 1527.95,
                },
              ],
              layPrices: [
                {
                  price: 1.16,
                  size: 106.2,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "240",
  },
  {
    openDate: "2026-01-06T04:10:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776647",
    competitionName: "WTA Canberra 2026",
    eventId: "35111184",
    eventName: "M Sherif v Ele Micic",
    marketId: "1.252306812",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252306812",
          marketName: "Match Odds",
          marketTime: 1767672600000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "9028621",
              runnerName: "Mayar Sherif",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.56,
                  size: 293.76,
                },
              ],
              layPrices: [
                {
                  price: 1.6,
                  size: 315.56,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "30472552",
              runnerName: "Elena Micic",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.68,
                  size: 1.39,
                },
              ],
              layPrices: [
                {
                  price: 2.76,
                  size: 1.36,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "495",
  },
  {
    openDate: "2026-01-06T04:10:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776545",
    competitionName: "Canberra Challenger 2026",
    eventId: "35117814",
    eventName: "Pinnington Jones v Bra Holt",
    marketId: "1.252383911",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252383911",
          marketName: "Match Odds",
          marketTime: 1767672600000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "38599044",
              runnerName: "Jack Pinnington Jones",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.56,
                  size: 199.59,
                },
              ],
              layPrices: [
                {
                  price: 1.57,
                  size: 2.4,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "10410230",
              runnerName: "Brandon Holt",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.74,
                  size: 388.45,
                },
              ],
              layPrices: [
                {
                  price: 2.8,
                  size: 111.2,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "299",
  },
  {
    openDate: "2026-01-06T04:20:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776599",
    competitionName: "Nonthaburi Challenger 2026",
    eventId: "35117908",
    eventName: "Max Jones v Colson",
    marketId: "1.252384612",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252384612",
          marketName: "Match Odds",
          marketTime: 1767673200000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "41413240",
              runnerName: "Maximus Jones",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.22,
                  size: 65.59,
                },
              ],
              layPrices: [
                {
                  price: 2.4,
                  size: 1.28,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "27405701",
              runnerName: "Tibo Colson",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.71,
                  size: 164.39,
                },
              ],
              layPrices: [
                {
                  price: 1.81,
                  size: 80.45,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "244",
  },
  {
    openDate: "2026-01-06T04:30:00.000+00:00",
    sportId: "2",
    sportName: "Tennis",
    competitionId: "12776429",
    competitionName: "ATP Brisbane 2026",
    eventId: "35110570",
    eventName: "N Kyrgios v Al Kovacevic",
    marketId: "1.252302623",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252302623",
          marketName: "Match Odds",
          marketTime: 1767673800000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "7299658",
              runnerName: "Nick Kyrgios",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.64,
                  size: 134.36,
                },
              ],
              layPrices: [
                {
                  price: 2.68,
                  size: 156.23,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "11439844",
              runnerName: "Aleksandar Kovacevic",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.6,
                  size: 33.46,
                },
              ],
              layPrices: [
                {
                  price: 1.61,
                  size: 1053.11,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
    liveStreamChannelId: "262",
  },
  {
    openDate: "2026-01-06T03:00:00.000+00:00",
    sportId: "sr:sport:2",
    sportName: "Basketball",
    competitionId: "sr:tournament:132",
    competitionName: "USA / NBA",
    eventId: "sr:match:62926079",
    eventName: "Portland Trail Blazers vs. Utah Jazz",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767668400000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Portland Trail Blazers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.01,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "draw",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 21.27,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Utah Jazz",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 21.27,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T03:00:00.000+00:00",
    sportId: "sr:sport:2",
    sportName: "Basketball",
    competitionId: "sr:tournament:132",
    competitionName: "USA / NBA",
    eventId: "sr:match:62924869",
    eventName: "LA Clippers vs. Golden State Warriors",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767668400000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "LA Clippers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.1,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "draw",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.97,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Golden State Warriors",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.97,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T03:07:31.000+00:00",
    sportId: "sr:sport:3",
    sportName: "Baseball",
    competitionId: "vbi:tournament:29702",
    competitionName: "Virtual Baseball / Virtual Baseball In-Play",
    eventId: "vbi:match:49585523",
    eventName: "Boston Red Sox vs. Chicago White Sox",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767668851000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "draw",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 6,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Boston Red Sox",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.85,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Chicago White Sox",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.85,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "SRL",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:15:00.000+00:00",
    sportId: "sr:sport:20",
    sportName: "Table Tennis",
    competitionId: "sr:tournament:36377",
    competitionName: "International / TT Elite Series",
    eventId: "sr:match:67471300",
    eventName: "Wisniewski, Bartlomiej vs. Radlo, Szymon",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767672900000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Wisniewski, Bartlomiej",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.04,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Radlo, Szymon",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 8.64,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:25:00.000+00:00",
    sportId: "sr:sport:20",
    sportName: "Table Tennis",
    competitionId: "sr:tournament:36377",
    competitionName: "International / TT Elite Series",
    eventId: "sr:match:67471308",
    eventName: "Zwolinski, Mariusz vs. Pisarczyk, Tomasz",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767673500000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Zwolinski, Mariusz",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.51,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Pisarczyk, Tomasz",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.39,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:30:00.000+00:00",
    sportId: "sr:sport:20",
    sportName: "Table Tennis",
    competitionId: "sr:tournament:36377",
    competitionName: "International / TT Elite Series",
    eventId: "sr:match:67471310",
    eventName: "Chrzescian, Radoslaw vs. Sklensky, Miroslav",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767673800000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:30:00.000+00:00",
    sportId: "sr:sport:20",
    sportName: "Table Tennis",
    competitionId: "sr:tournament:36377",
    competitionName: "International / TT Elite Series",
    eventId: "sr:match:67425928",
    eventName: "Marud, Grzegorz vs. Urban, Wojciech",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767673800000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:35:00.000+00:00",
    sportId: "sr:sport:20",
    sportName: "Table Tennis",
    competitionId: "sr:tournament:36377",
    competitionName: "TT Elite Series",
    eventId: "sr:match:67471312",
    eventName: "Pytlas, Wojciech vs. Kaczmarek, Jakub",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767674100000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Pytlas, Wojciech",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.92,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Kaczmarek, Jakub",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.78,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:35:00.000+00:00",
    sportId: "sr:sport:20",
    sportName: "Table Tennis",
    competitionId: "sr:tournament:36377",
    competitionName: "International / TT Elite Series",
    eventId: "sr:match:67471306",
    eventName: "Baca, Jaroslav vs. Dabrowski, Igor",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767674100000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Baca, Jaroslav",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Dabrowski, Igor",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.73,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T04:30:00.000+00:00",
    sportId: "sr:sport:23",
    sportName: "Volleyball",
    competitionId: "sr:tournament:32175",
    competitionName: "Russia / Pro League",
    eventId: "sr:match:67470574",
    eventName: "Molot vs. Vityaz",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767673800000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Molot",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.3,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Vityaz",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.54,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T02:30:00.000+00:00",
    sportId: "sr:sport:4",
    sportName: "Ice Hockey",
    competitionId: "sr:tournament:234",
    competitionName: "USA / NHL",
    eventId: "sr:match:62075460",
    eventName: "Calgary Flames vs. Seattle Kraken",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767666600000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Calgary Flames",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.55,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "draw",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.2,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Seattle Kraken",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.2,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-06T03:30:00.000+00:00",
    sportId: "sr:sport:4",
    sportName: "Ice Hockey",
    competitionId: "sr:tournament:234",
    competitionName: "USA / NHL",
    eventId: "sr:match:62075462",
    eventName: "Los Angeles Kings vs. Minnesota Wild",
    status: "IN_PLAY",
    providerName: "SportRadar",
    markets: {
      matchOdds: [
        {
          marketId: "340",
          marketName: "Winner (incl. super over)",
          marketTime: 1767670200000,
          marketType: "MATCH_ODDS",
          status: "IN_PLAY",
          runners: [
            {
              runnerName: "Los Angeles Kings",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.55,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "draw",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.31,
                  size: 0,
                },
              ],
            },
            {
              runnerName: "Minnesota Wild",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.31,
                  size: 0,
                },
              ],
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: true,
      fancySuspended: false,
      fancyDisabled: false,
    },
    catName: "exclusive",
    enabled: true,
    premiumEnabled: true,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2025-02-05T17:15:00.000+00:00",
    customOpenDate: "2026-01-09T14:00:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "12559935",
    competitionName: "Women's Premier League",
    eventId: "32127028",
    customEventName: "Women's Premier League",
    eventName: "Women's Premier League",
    marketId: "1.252059844",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252059844",
          marketName: "Winner",
          marketTime: 1767967200000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "67071071",
              runnerName: "Mumbai Indians W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.85,
                  size: 52.83,
                },
              ],
              layPrices: [
                {
                  price: 3.9,
                  size: 1.11,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "80232363",
              runnerName: "Up Warriorz W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 4.9,
                  size: 38.61,
                },
              ],
              layPrices: [
                {
                  price: 5.3,
                  size: 1.11,
                },
              ],
              sort: "2",
            },
            {
              runnerId: "80067232",
              runnerName: "Royal Challengers Bengaluru W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 4.5,
                  size: 15.25,
                },
              ],
              layPrices: [
                {
                  price: 9,
                  size: 5,
                },
              ],
              sort: "3",
            },
            {
              runnerId: "66528615",
              runnerName: "Delhi Capitals W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 5,
                  size: 1,
                },
              ],
              layPrices: [
                {
                  price: 9,
                  size: 5,
                },
              ],
              sort: "4",
            },
            {
              runnerId: "66744658",
              runnerName: "Gujarat Giants W",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 7.6,
                  size: 1,
                },
              ],
              layPrices: [
                {
                  price: 13,
                  size: 5,
                },
              ],
              sort: "5",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2025-12-14T09:15:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "10328858",
    competitionName: "Twenty20 Big Bash",
    eventId: "27996014",
    customEventName: "Twenty20 Big Bash",
    eventName: " Twenty20 Big Bash",
    marketId: "1.249873540",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.249873540",
          marketName: "Winner 2025/26",
          marketTime: 1765703700000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "5728188",
              runnerName: "Perth Scorchers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.65,
                  size: 100.28,
                },
              ],
              layPrices: [
                {
                  price: 3.7,
                  size: 49.58,
                },
              ],
              sort: "2",
            },
            {
              runnerId: "5728193",
              runnerName: "Hobart Hurricanes",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 3.75,
                  size: 35.22,
                },
              ],
              layPrices: [
                {
                  price: 3.85,
                  size: 394.55,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "5728187",
              runnerName: "Melbourne Stars",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 4.2,
                  size: 130.81,
                },
              ],
              layPrices: [
                {
                  price: 4.3,
                  size: 40.19,
                },
              ],
              sort: "3",
            },
            {
              runnerId: "5728225",
              runnerName: "Sydney Sixers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 8.8,
                  size: 20.99,
                },
              ],
              layPrices: [
                {
                  price: 9.2,
                  size: 11.92,
                },
              ],
              sort: "5",
            },
            {
              runnerId: "5728189",
              runnerName: "Melbourne Renegades",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 23,
                  size: 13.38,
                },
              ],
              layPrices: [
                {
                  price: 26,
                  size: 4.96,
                },
              ],
              sort: "6",
            },
            {
              runnerId: "5728253",
              runnerName: "Adelaide Strikers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 28,
                  size: 4.46,
                },
              ],
              layPrices: [
                {
                  price: 32,
                  size: 5.38,
                },
              ],
              sort: "4",
            },
            {
              runnerId: "5728194",
              runnerName: "Brisbane Heat",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 32,
                  size: 7.91,
                },
              ],
              layPrices: [
                {
                  price: 36,
                  size: 5,
                },
              ],
              sort: "8",
            },
            {
              runnerId: "5728190",
              runnerName: "Sydney Thunder",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 190,
                  size: 1.49,
                },
              ],
              layPrices: [
                {
                  price: 400,
                  size: 2.1,
                },
              ],
              sort: "7",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: true,
    favoritePriority: 3,
  },
  {
    openDate: "2026-01-06T08:15:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "10328858",
    competitionName: "Twenty20 Big Bash",
    eventId: "35115080",
    eventName: "Adelaide Strikers v Sydney Thunder",
    marketId: "1.252376930",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252376930",
          marketName: "Match Odds",
          marketTime: 1767687300000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "5728253",
              runnerName: "Adelaide Strikers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.8,
                  size: 1997.08,
                },
              ],
              layPrices: [
                {
                  price: 1.81,
                  size: 103.77,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "5728190",
              runnerName: "Sydney Thunder",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.22,
                  size: 660.43,
                },
              ],
              layPrices: [
                {
                  price: 2.24,
                  size: 86.49,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
      enableToss: true,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: true,
    favoritePriority: 1,
    liveStreamChannelId: "7112",
  },
  {
    openDate: "2026-01-06T15:30:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "12546072",
    competitionName: "SA20",
    eventId: "35115171",
    eventName: "Mi Cape Town v Joburg Super Kings",
    marketId: "1.252351191",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252351191",
          marketName: "Match Odds",
          marketTime: 1767713400000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "78513514",
              runnerName: "MI Cape Town",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.73,
                  size: 92.53,
                },
              ],
              layPrices: [
                {
                  price: 1.8,
                  size: 14.73,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "51571507",
              runnerName: "Joburg Super Kings",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.24,
                  size: 11.84,
                },
              ],
              layPrices: [
                {
                  price: 2.36,
                  size: 4.7,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
      enableToss: true,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: true,
    favoritePriority: 1,
    liveStreamChannelId: "7102",
  },
  {
    openDate: "2026-01-07T08:15:00.000+00:00",
    sportId: "4",
    sportName: "Cricket",
    competitionId: "10328858",
    competitionName: "Twenty20 Big Bash",
    eventId: "35115137",
    eventName: "Perth Scorchers v Melbourne Renegades",
    marketId: "1.252381865",
    status: "IN_PLAY",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252381865",
          marketName: "Match Odds",
          marketTime: 1767773700000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          runners: [
            {
              runnerId: "5728188",
              runnerName: "Perth Scorchers",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 1.63,
                  size: 23.86,
                },
              ],
              layPrices: [
                {
                  price: 1.64,
                  size: 7.76,
                },
              ],
              sort: "1",
            },
            {
              runnerId: "5728189",
              runnerName: "Melbourne Renegades",
              status: "ACTIVE",
              backPrices: [
                {
                  price: 2.56,
                  size: 14.6,
                },
              ],
              layPrices: [
                {
                  price: 2.6,
                  size: 14.96,
                },
              ],
              sort: "2",
            },
          ],
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: true,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
      enableToss: true,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: true,
    favoritePriority: 2,
  },

  {
    openDate: "2026-01-06T00:00:00.000+00:00",
    customOpenDate: "2026-01-06T04:30:00.000+00:00",
    sportId: "99990",
    sportName: "Binary",
    competitionId: "999999993",
    competitionName: "Binary",
    eventId: "1767657600",
    eventName: "Binary",
    status: "IN_PLAY",
    providerName: "RX",
    markets: {
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: true,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: true,
    virtualEvent: false,
    favorite: false,
  },
];
