export const newLaunch = [
  {
    houseId: 16,
    gameId: "151180",
    category: "roulette",
    gameCode: "MAC88-LRO101",
    gameName: "VR Lightning Roulette",
    urlThumb: "https://cdn.mac88.com/mac88/VLRT.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151180/__LIGHTNING-ROULETTE.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -35,
    providerTag: "MAC88 VIRTUALS",
  },
  {
    houseId: 16,
    gameId: "151163",
    category: "slot games",
    gameCode: "MAC88-CDGT101",
    gameName: "Dragon Tower",
    urlThumb: "https://cdn.mac88.com/mac88/dragontower.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151163/__1-DRAGON-TOWER.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -34,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151164",
    category: "slot games",
    gameCode: "MAC88-COPK101",
    gameName: "Packs",
    urlThumb: "https://cdn.mac88.com/mac88/packs.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151164/__2-PACKS.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -33,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151165",
    category: "aviator",
    gameCode: "MAC88-CNB101",
    gameName: "Naughty Button",
    urlThumb: "https://cdn.mac88.com/mac88/naughtybutton.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151165/NAUGHTY-BUTTON.png",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -31,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151154",
    category: "Others",
    gameCode: "MAC88-HRT101",
    gameName: "Race Track",
    urlThumb: "https://cdn.mac88.com/mac88/racetrack.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151154/__RACE-TRACK.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -30,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151133",
    category: "Others",
    gameCode: "MAC88-JM101",
    gameName: "Jhandi Munda",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/jhandimunda.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151133/__JHANDI-MUNDA.webp",
    providerName: "MAC88",
    subProviderName: "Fun Games",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -29,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151080",
    category: "slot games",
    gameCode: "MAC88-CVO101",
    gameName: "Twistx",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/twistx.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151080/TWIST-X.png",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -27,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151095",
    category: "slot games",
    gameCode: "MAC88-CRPS101",
    gameName: "Rock Paper Scissors",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/rps.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151095/rock paper.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -26,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151178",
    category: "slot games",
    gameCode: "MAC88-CVOI101",
    gameName: "The Voice",
    urlThumb: "https://cdn.mac88.com/mac88/voice.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151178/__1-THE-VOICE.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -20,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "600004",
    category: "scratch cards",
    gameCode: "jili_jackpot_fishing",
    gameName: "Jackpot Fishing",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Jackpot_Fishing.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_jackpot_fishing.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: -16,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600001",
    category: "scratch cards",
    gameCode: "jili_royal_fishing",
    gameName: "Royal Fishing",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Royal_Fishing.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_royal_fishing.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: -14,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600006",
    category: "scratch cards",
    gameCode: "jili_mega_fishing",
    gameName: "Mega Fishing",
    urlThumb: "https://cdn.dreamdelhi.com/jili/Jili_Mega_Fishing.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_mega_fishing.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: -13,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "151179",
    category: "slot games",
    gameCode: "MAC88-CDRND101",
    gameName: "Deal Or No Deal",
    urlThumb: "https://cdn.mac88.com/mac88/dnd.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151179/__2-DEAL-NO-DEAL.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -12,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151170",
    category: "slot games",
    gameCode: "MAC88-CSN101",
    gameName: "Snakes",
    urlThumb: "https://cdn.mac88.com/mac88/snakes.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151170/__3-SNAKES.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: -11,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "151162",
    category: "Others",
    gameCode: "MAC88-CPUM101",
    gameName: "Pump",
    urlThumb: "https://cdn.mac88.com/mac88/pump.webp",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/151162/PUMP.png",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming Virtual",
    superProviderName: "MACHUB",
    tag: "new_launch",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 7,
    providerTag: "MAC88 FUN GAMES",
  },
  {
    houseId: 16,
    gameId: "150007",
    category: "andar bahar",
    gameCode: "MAC88-XAB101",
    gameName: "Andar Bahar",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/andar_bahar.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/ab.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 18,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150002",
    category: "live baccarat",
    gameCode: "MAC88-XBAC101",
    gameName: "BACCARAT",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/baccarat_mac88.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/baccarat.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 19,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150054",
    category: "teenpatti",
    gameCode: "MAC88-ZMTP101",
    gameName: "Muflis Teenpatti",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/mtp.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-Y1MTP101.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 20,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150031",
    category: "others",
    gameCode: "MAC88-YBOC102",
    gameName: "Bollywood Casino ",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/bollywood_casino.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/bc.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 21,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150001",
    category: "dragon tiger",
    gameCode: "MAC88-YDT102",
    gameName: "Dragon Tiger",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/dt_mac88.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-YDT102.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 26,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150067",
    category: "dragon tiger",
    gameCode: "MAC88-DT2101",
    gameName: "Dragon Tiger 2",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/dt2.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-DT2101.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 27,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150042",
    category: "teenpatti",
    gameCode: "MAC88-X2TP101",
    gameName: "Instant 2 Cards Teenpatti",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/2_card_tp.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-X2TP101.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 31,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150006",
    category: "lucky7",
    gameCode: "MAC88-YLK7101",
    gameName: "Lucky7",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/lucky_7.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/l7.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 34,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150032",
    category: "live poker",
    gameCode: "MAC88-Y1POK101",
    gameName: "Poker 1-Day",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/poker_1_day.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/poker.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 42,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150017",
    category: "others",
    gameCode: "MAC88-YRTT102",
    gameName: "Race 20",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/race_20.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-YRTT102.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: 45,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150004",
    category: "live roulette",
    gameCode: "MAC88-XRT101",
    gameName: "Roulette",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/roulette_mac88.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-XRT101.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 48,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150003",
    category: "live sic bo",
    gameCode: "MAC88-XSB101",
    gameName: "Sic Bo",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/sicbo_mac88.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/sicbo.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 49,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150023",
    category: "teenpatti",
    gameCode: "MAC88-YTTP102",
    gameName: "Test Teenpatti",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/teenpatti_test.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/ttp.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 54,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150035",
    category: "Cricketwar",
    gameCode: "MAC88-Y15C101",
    gameName: "5 Five Cricket",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/5_five_cricket.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/5c.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: 55,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150036",
    category: "dragon tiger",
    gameCode: "MAC88-X1DT101",
    gameName: "1 Day Dragon Tiger",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/dt_1day.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/dt1d.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150033",
    category: "teenpatti",
    gameCode: "MAC88-YTPTT101",
    gameName: "20-20 Teenpatti",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/20_20_teenpatti.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/32c.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150066",
    category: "teenpatti",
    gameCode: "MAC88-TPTT2101",
    gameName: "20 20 Teenpatti 2",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/2020tp2.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-TPTT2101.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "150010",
    category: "32cards",
    gameCode: "MAC88-Y32CA102",
    gameName: "32 Cards",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/32_cards.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/32%20Cards.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "600062",
    category: "slot games",
    gameCode: "",
    gameName: "Ali Baba",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Ali_Baba.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/jili_ali_baba.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "150014",
    category: "others",
    gameCode: "MAC88-YA3101",
    gameName: "Amar Akbar Anthony",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/amar_akbar_anthony.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/MAC88-YA3101.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "imlive90238",
    category: "Roulette",
    gameCode: "MC8",
    gameName: "Auto-Roulette",
    urlThumb:
      "https://files.mac444.com/Document/Game/Auto-Roulette_1759912108476.2192.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_ar.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "600077",
    category: "slot games",
    gameCode: "jili_bonus_hunter",
    gameName: "Bonus Hunter",
    urlThumb: "https://cdn.dreamcasino.live/gap_casino/jili_bonus_hunter.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_bonus_hunter.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600007",
    category: "scratch cards",
    gameCode: "jili_boom_legend",
    gameName: "Boom Legend",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Boom_Legend.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_boom_legend.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600046",
    category: "slot games",
    gameCode: "jili_boxing_king",
    gameName: "Boxing King",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Boxing_King.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_boxing_king.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600020",
    category: "slot games",
    gameCode: "jili_chin_shi_huang",
    gameName: "Chin Shi Huang",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Chin_Shj_Huang.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_chin_shi_huang.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "425026",
    category: "lottery",
    gameCode: "kingmidas_coin_toss",
    gameName: "Coin Toss",
    urlThumb: "https://cdn.dreamdelhi.com/kingmidas/coin_toss.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/kingmidas_coin_toss.webp",
    providerName: "KINGMIDAS",
    subProviderName: "KINGMAKER",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "KINGMAKER",
  },
  {
    houseId: 16,
    gameId: "600029",
    category: "lucky7",
    gameCode: "jili_crazy777",
    gameName: "Crazy777",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Crazy_777.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/jili_crazy777.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "imlive90262",
    category: "Fun",
    gameCode: "MC8",
    gameName: "Crazy Time",
    urlThumb:
      "https://files.mac444.com/Document/Game/Crazy-Time-264_1761546899551.3264.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_ct.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "600003",
    category: "scratch cards",
    gameCode: "jili_dinosaur_tycoon",
    gameName: "Dinosaur Tycoon",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Dinosaur_Tycoon.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_dinosaur_tycoon.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "imlive90006",
    category: "Dragon Tiger",
    gameCode: "MC8",
    gameName: "Dragon Tiger",
    urlThumb:
      "http://files.mac444.com/Document/Game/dragon_tiger_banner_1080x1080_2021_02_01_1758880785307.8684.png",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_dt.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "150063",
    category: "Live Game Shows",
    gameCode: "MAC88-ZDC101",
    gameName: "Dream Wheel",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/dw.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/150063/dream_wheel.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "600120",
    category: "slot games",
    gameCode: "jili_fortune_gems_2",
    gameName: "Fortune Gems 2",
    urlThumb: "https://cdn.dreamdelhi.com/jili/fortune_gems_2.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/v2/jili_fortune_gems_2.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600140",
    category: "slot games",
    gameCode: "jili_fortune_gems_3",
    gameName: "Fortune Gems 3",
    urlThumb: "https://cdn.dreamdelhi.com/jili/fortune_gems_3.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/v2/jili_fortune_gems_3.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "imlive90273",
    category: "Fun",
    gameCode: "MC8",
    gameName: "Lightning Dice",
    urlThumb:
      "https://files.mac444.com/Document/Game/Lightning-Dice-275_1763031524519.3403.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_ld.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "imlive90532",
    category: "Fun",
    gameCode: "MC8",
    gameName: "Marble Race",
    urlThumb:
      "https://files.mac444.com/Document/Game/Marble-Race-533_1761559243542.361.jpg",
    urlBackground: null,
    trendingThumbnail:
      "https://cdn.uvwin2024.co/casino/trending_thumbnail/825521/__6-MARBLE-RACE-135x180-PIXELS.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "600085",
    category: "slot games",
    gameCode: "jili_master_tiger",
    gameName: "Master Tiger",
    urlThumb: "https://cdn.dreamcasino.live/gap_casino/jili_master_tiger.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_master_tiger.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600067",
    category: "slot games",
    gameCode: "jili_mega_ace",
    gameName: "Mega Ace",
    urlThumb: "https://cdn.dreamcasino.live/gap_casino/jili_mega_ace.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/jili_mega_ace.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600044",
    category: "slot games",
    gameCode: "jili_money_coming",
    gameName: "Money Coming",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Money_Coming.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/trending/jili_moneycoming.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600048",
    category: "slot games",
    gameCode: "jili_pharaoh_treasure",
    gameName: "Pharaoh Treasure",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_Pharaoh_Treasure.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_pharaoh_treasure.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "204172",
    category: "slot games",
    gameCode: "gmz_pilot_coin",
    gameName: "Pilot Coin",
    urlThumb: "https://cdn.dreamcasino.live/gmz_pilot_coin/thumb.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/updated/gmz_pilot_coin.webp",
    providerName: "DC",
    subProviderName: "Gamzix",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "GAMZIX",
  },
  {
    houseId: 16,
    gameId: "600082",
    category: "slot games",
    gameCode: "jili_pirate_queen",
    gameName: "Pirate Queen",
    urlThumb: "https://cdn.dreamcasino.live/gap_casino/jili_pirate_queen.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_pirate_queen.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "600115",
    category: "others",
    gameCode: "jili_pusoy_go",
    gameName: "Pusoy Go",
    urlThumb: "https://cdn.dreamcasino.live/gap_casino/jili_pusoy_go.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/v2/jili_pusoy_go.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "imlive90239",
    category: "Roulette",
    gameCode: "MC8",
    gameName: "Red Door Roulette",
    urlThumb:
      "https://files.mac444.com/Document/Game/Red-Door-Roulette-241_1761553694577.769.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_rdr.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "600028",
    category: "slot games",
    gameCode: "jili_sevensevenseven",
    gameName: "SevenSevenSeven",
    urlThumb: "https://cdn.dreamcasino.live/jili/Jili_777.webp",
    urlBackground: "",
    trendingThumbnail:
      "https://cdn.dreamdelhi.com/updated/jili_sevensevenseven.webp",
    providerName: "JiLi",
    subProviderName: "JiLi Gaming",
    superProviderName: "GAP",
    tag: "slot",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: true,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "JILI",
  },
  {
    houseId: 16,
    gameId: "imlive90017",
    category: "Baccarat",
    gameCode: "MC8",
    gameName: "Speed Baccarat A",
    urlThumb:
      "https://files.mac444.com/Document/Game/Speed-Baccarat-A-17_1760687319702.7883.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_speedb.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "150034",
    category: "Cricketwar",
    gameCode: "MAC88-Y1SPO101",
    gameName: "SUPER OVER ONE DAY",
    urlThumb: "https://cdn.dreamdelhi.com/mac88/super_over.webp",
    urlBackground: "",
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/so.webp",
    providerName: "MAC88",
    subProviderName: "Mac88 Gaming",
    superProviderName: "MACHUB",
    tag: "recommended_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "MAC88 LIVE",
  },
  {
    houseId: 16,
    gameId: "imlive90003",
    category: "Fun",
    gameCode: "MC8",
    gameName: "Super Sic Bo",
    urlThumb:
      "https://files.mac444.com/Document/Game/Super-Color-Game-536_1761558817073.074.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_ssb.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
  {
    houseId: 16,
    gameId: "imlive90235",
    category: "Roulette",
    gameCode: "MC8",
    gameName: "XXXtreme Lightning Roulette",
    urlThumb:
      "https://files.mac444.com/Document/Game/XXXtreme-Lightning-Roulette-237_1761546976320.9731.jpg",
    urlBackground: null,
    trendingThumbnail: "https://cdn.dreamdelhi.com/trending/evo_xlr.webp",
    providerName: "MAC88",
    subProviderName: "MAC88",
    superProviderName: "MAC444",
    tag: "live_casino_games",
    status: null,
    enabled: true,
    favourite: false,
    bonusEnabled: false,
    state: "ENABLED",
    trending: true,
    priority: null,
    providerTag: "EVOLUTION",
  },
];
