import { ReactComponent as Kabaddi } from "../../assets/images/sidebar/kabaddi.svg?react";
import { ReactComponent as Baseball } from "../../assets/images/sidebar/baseball.svg?react";
import { ReactComponent as Basketball } from "../../assets/images/sidebar/basketball.svg?react";
import { ReactComponent as Binary } from "../../assets/images/sidebar/binary.svg?react";
import { ReactComponent as Cricket } from "../../assets/images/sidebar/cricket.svg?react";
import { ReactComponent as Darts } from "../../assets/images/sidebar/darts.svg?react";
import { ReactComponent as Football } from "../../assets/images/sidebar/football.svg?react";
import { ReactComponent as Futsal } from "../../assets/images/sidebar/futsal.svg?react";
import { ReactComponent as GreyHound } from "../../assets/images/sidebar/grey_hound.svg?react";
import { ReactComponent as HorseRacing } from "../../assets/images/sidebar/horse_racing.svg?react";
import { ReactComponent as IceHockey } from "../../assets/images/sidebar/ice-hockey.svg?react";
import { ReactComponent as Rugby } from "../../assets/images/sidebar/rugby.svg?react";
import { ReactComponent as MMA } from "../../assets/images/sidebar/mma.svg?react";
import { ReactComponent as MultiMarkets } from "../../assets/images/sidebar/multi_markets.svg?react";
import { ReactComponent as Politics } from "../../assets/images/sidebar/politics.svg?react";
import { ReactComponent as Promotions } from "../../assets/images/sidebar/promotions.svg?react";
import { ReactComponent as TableTennis } from "../../assets/images/sidebar/table_tennis.svg?react";
import { ReactComponent as Tennis } from "../../assets/images/sidebar/tennis.svg?react";
import { ReactComponent as Volleyball } from "../../assets/images/sidebar/volleyball.svg?react";

import { ReactComponent as AccountStatement } from "../../assets/images/sidebar/account_statement.svg?react";
import { ReactComponent as AffiliateIcon } from "../../assets/images/sidebar/affiliate-program.svg?react";
import { ReactComponent as BonusStatement } from "../../assets/images/sidebar/bonus_statement.svg?react";
import { ReactComponent as Deposit } from "../../assets/images/sidebar/deposit.svg?react";
import { ReactComponent as GameRules } from "../../assets/images/sidebar/game_rules.svg?react";
import { ReactComponent as Logout } from "../../assets/images/sidebar/logout.svg?react";
import { ReactComponent as MyBets } from "../../assets/images/sidebar/my_bets.svg?react";
import { ReactComponent as MyProfile } from "../../assets/images/sidebar/my_profile.svg?react";
import { ReactComponent as MyTransaction } from "../../assets/images/sidebar/my_transaction.svg?react";
import { ReactComponent as MyWallet } from "../../assets/images/sidebar/my_wallet.svg?react";
import { ReactComponent as ProfitLoss } from "../../assets/images/sidebar/profit_loss.svg?react";
import { ReactComponent as StakeSettings } from "../../assets/images/sidebar/stake_settings.svg?react";
import { ReactComponent as TermsPolicy } from "../../assets/images/sidebar/TermsPolicy.svg?react";
import { ReactComponent as TurnoverHistory } from "../../assets/images/sidebar/turnover_history.svg?react";
import { ReactComponent as Withdraw } from "../../assets/images/sidebar/withdraw.svg?react";
import { LanguageOutlined } from "@material-ui/icons";
import { ReactComponent as ThemeBtn } from "../../assets/images/home/tiles/theme_svg.svg?react";
import { ReactComponent as TwoFactorIcon } from "../../assets/images/MyProfileIcons/two_factor_icon.svg?react";

export const sideHeaderTabs = [
  {
    id: "4",
    text: "cricket",
    langKey: "cricket",
    img: Cricket,
    route: "/exchange_sports/cricket",
    showWithoutLogin: true,
  },
  {
    id: "1",
    text: "football",
    langKey: "football",
    img: Football,
    route: "/exchange_sports/football",
    showWithoutLogin: true,
  },
  {
    id: "2",
    text: "tennis",
    langKey: "tennis",
    img: Tennis,
    route: "/exchange_sports/tennis",
    showWithoutLogin: true,
  },
  {
    id: "99994",
    text: "Kabaddi",
    langKey: "kabaddi",
    img: Kabaddi,
    route: "/exchange_sports/kabaddi",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:2",
    text: "Basketball",
    langKey: "basketball",
    img: Basketball,
    route: "/exchange_sports/basketball",
    showWithoutLogin: true,
  },
  {
    id: "7511",
    text: "Baseball",
    langKey: "baseball",
    img: Baseball,
    route: "/exchange_sports/baseball",
    showWithoutLogin: true,
  },
  {
    id: "4339",
    text: "GreyHound",
    langKey: "greyhound",
    img: GreyHound,
    route: "/exchange_sports/greyhound",
    showWithoutLogin: true,
  },
  {
    id: "7",
    text: "Horse Race",
    langKey: "horse_race",
    img: HorseRacing,
    route: "/exchange_sports/horseracing",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:23",
    text: "Volleyball",
    langKey: "volleyball",
    img: Volleyball,
    route: "/exchange_sports/volleyball",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:22",
    text: "Darts",
    langKey: "darts",
    img: Darts,
    route: "/exchange_sports/darts",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:29",
    text: "Futsal",
    langKey: "futsal",
    img: Futsal,
    route: "/exchange_sports/futsal",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:20",
    text: "Table Tennis",
    langKey: "table_tennis",
    img: TableTennis,
    route: "/exchange_sports/tabletennis",
    showWithoutLogin: true,
  },
  {
    id: "99990",
    text: "Binary",
    langKey: "binary",
    img: Binary,
    route: "/exchange_sports/binary",
    showWithoutLogin: true,
  },
  {
    id: "2378961",
    text: "Politics",
    langKey: "politics",
    img: Politics,
    route: "/exchange_sports/politics",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:4",
    text: "Ice Hockey",
    langKey: "ice_hockey",
    img: IceHockey,
    route: "/exchange_sports/icehockey",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:117",
    text: "MMA",
    img: MMA,
    langKey: "mma",
    route: "/exchange_sports/mma",
    showWithoutLogin: true,
  },
  {
    id: "sr:sport:12",
    text: "Rugby",
    langKey: "rugby",
    img: Rugby,
    route: "/exchange_sports/rugby",
    showWithoutLogin: true,
  },
  {
    id: "23",
    text: "Multi markets",
    langKey: "multimarkets",
    img: MultiMarkets,
    route: "/exchange_sports/multi-markets",
    showWithoutLogin: true,
  },
];

export const otherMenuTabs = [
  {
    id: 9,
    text: "Deposit",
    langKey: "deposit",
    img: Deposit,
    route: "/transaction/deposit",
    showWithoutLogin: false,
  },
  {
    id: 10,
    text: "Withdraw",
    langKey: "withdraw",
    img: Withdraw,
    route: "/transaction/withdraw",
    showWithoutLogin: false,
  },
  {
    id: 24,
    text: "Promotions",
    langKey: "promotions",
    img: Promotions,
    route: "/promotions",
    showWithoutLogin: true,
  },
  {
    id: 11,
    text: "My Bets",
    langKey: "my_bets",
    img: MyBets,
    route: "/my_bets",
    showWithoutLogin: false,
  },
  {
    id: 12,
    text: "My Wallet",
    langKey: "my_wallet",
    img: MyWallet,
    route: "/my_wallet",
    showWithoutLogin: false,
  },
  {
    id: 13,
    text: "Affiliate Program",
    langKey: "affiliate_program",
    img: AffiliateIcon,
    route: "/affiliate_program",
    showWithoutLogin: false,
  },
  {
    id: 14,
    text: "Affiliate (Refer & Earn)",
    langKey: "affiliate_refer_earn",
    img: AffiliateIcon,
    route: "/affiliate_refer_earn",
    showWithoutLogin: false,
  },
  {
    id: 15,
    text: "Betting Profit & Loss",
    langKey: "betting_profit_and_loss",
    img: ProfitLoss,
    route: "/pl_statement",
    showWithoutLogin: false,
  },
  {
    id: 16,
    text: "Turnover history",
    langKey: "turnover_history",
    img: TurnoverHistory,
    route: "/bonus/turnover_history",
    showWithoutLogin: false,
  },
  {
    id: 17,
    text: "Account Statement",
    langKey: "account_statement",
    img: AccountStatement,
    route: "/account_statement",
    showWithoutLogin: false,
  },
  {
    id: 18,
    text: "Bonus Statement",
    langKey: "bonus_statement",
    img: BonusStatement,
    route: "/bonus_statement",
    showWithoutLogin: false,
  },
  {
    id: 25,
    text: "Deposit Turnover",
    langKey: "deposit_turnover",
    img: TurnoverHistory,
    route: "/deposit-turnover",
    showWithoutLogin: false,
  },
  {
    id: 19,
    text: "My Transaction",
    langKey: "my_transactions",
    img: MyTransaction,
    route: "/my_transactions",
    showWithoutLogin: false,
  },
  {
    id: 20,
    text: "Stake Settings",
    langKey: "stake_settings",
    img: StakeSettings,
    route: "/set-button-variables",
    showWithoutLogin: false,
  },
  {
    id: 8,
    text: "Game Rules",
    langKey: "game_rules",
    img: GameRules,
    route: "/game-rules",
    showWithoutLogin: true,
  },
  {
    id: 21,
    text: "My Profile",
    langKey: "my_profile",
    img: MyProfile,
    route: "/profile?tab=0",
    showWithoutLogin: false,
  },
  {
    id: 28,
    text: "Two Factor Authentication",
    langKey: "two_factor_auth",
    img: TwoFactorIcon,
    route: "/profile?tab=2",
    showWithoutLogin: false,
    blink: true,
  },
  {
    id: 26,
    text: "Languages",
    langKey: "language",
    img: LanguageOutlined,
    route: "/languages",
    showWithoutLogin: true,
  },
];

export const securityAndLogout = [
  {
    id: 21,
    text: "Terms & Policy",
    langKey: "terms_and_policy",
    img: TermsPolicy,
    route: "/terms-conditions",
    showWithoutLogin: true,
  },
  {
    id: 22,
    text: "Logout",
    langKey: "logout",
    img: Logout,
    route: "",
    showWithoutLogin: false,
  },
];

export const securityAndLogoutForFairplay = [
  {
    id: 21,
    text: "Terms",
    langKey: "terms_conditions",
    img: TermsPolicy,
    route: "/fairplay-terms-conditions",
    showWithoutLogin: true,
  },
  {
    id: 23,
    text: "Privacy Policy",
    langKey: "privacy_policy",
    img: GameRules,
    route: "/fairplay_policy",
    showWithoutLogin: true,
  },
  {
    id: 22,
    text: "Logout",
    langKey: "logout",
    img: Logout,
    route: "",
    showWithoutLogin: false,
  },
];

// Static competitions data
export const competitionsData = [
  // Cricket Competitions (sportId: "4")
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "12546072",
    competitionName: "SA20",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:50110",
    competitionName: "Pakistan / Presidents Trophy",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:33207",
    competitionName: "Simulated Reality League / Big Bash League SRL",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "10479856",
    competitionName: "Super Smash T20",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:36805",
    competitionName: "Simulated Reality League / Pakistan Super League SRL",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "12444379",
    competitionName: "The Ashes",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "9962116",
    competitionName: "One Day Internationals",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:36807",
    competitionName: "Simulated Reality League / T20 International SRL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:32201",
    competitionName: "Simulated Reality League / Premier League SRL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:36803",
    competitionName: "Simulated Reality League / Caribbean Premier League SRL",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "12652316",
    competitionName: "Zimbabwe Domestic T20",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:46519",
    competitionName: "Simulated Reality League / Super Smash SRL",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "12161756",
    competitionName: "Bangladesh Premier League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:21",
    competitionId: "sr:tournament:39175",
    competitionName: "Simulated Reality League / SA T20 League SRL",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "12162210",
    competitionName: "Womens Super Smash T20",
    enabled: true,
  },
  {
    providerId: "RX",
    sportId: "4",
    competitionId: "RX123",
    competitionName: "Other",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "10328858",
    competitionName: "Twenty20 Big Bash",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "4",
    competitionId: "12559935",
    competitionName: "Women's Premier League",
    enabled: true,
  },
  // Football Competitions (sportId: "1")
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "11869656",
    competitionName: "Ethiopian Premier League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "822165",
    competitionName: "Israeli Premier League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:33656",
    competitionName: "Ethiopia / Premier League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12306595",
    competitionName: "Gambian GFA League 1st Division",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:19724",
    competitionName: "Bahrain / First Division",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:270",
    competitionName: "International / Africa Cup of Nations",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "3796898",
    competitionName: "Jamaican Premier League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12211021",
    competitionName: "Greek Cup",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12209528",
    competitionName: "Africa Cup of Nations",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "7836682",
    competitionName: "Myanmar National League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:2298",
    competitionName: "Saudi Arabia / Division 1",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:239",
    competitionName: "Portugal / Liga Portugal 2",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:19248",
    competitionName: "Myanmar / National League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:853",
    competitionName: "International Clubs / Club Friendly Games",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:48515",
    competitionName: "Singapore / Premier League 2",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12511339",
    competitionName: "English U21 Pro Development League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:20560",
    competitionName: "Indonesia / Championship",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "11997927",
    competitionName: "Indonesian Championship",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:43125",
    competitionName: "Malaysia / Liga A1",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:939",
    competitionName: "Kuwait / Crown Prince Cup",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:18",
    competitionName: "England / Championship",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "2315454",
    competitionName: "Saudi 1st Division",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "9513",
    competitionName: "Portuguese Segunda Liga",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:23517",
    competitionName: "Brazil / U20 Copa Sao Paulo de Juniores",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "4431442",
    competitionName: "Algerian Ligue 1",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:29842",
    competitionName: "England Amateur / U21 Professional Development League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "822951",
    competitionName: "Indonesian Super League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12205806",
    competitionName: "Israeli National League",
    enabled: true,
  },
  {
    providerId: "RX",
    sportId: "1",
    competitionId: "RX123",
    competitionName: "Other",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:182",
    competitionName: "France / Ligue 2",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:36193",
    competitionName: "Egypt / League Cup",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:1133",
    competitionName: "Portugal / U19 Campeonato Nacional",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:841",
    competitionName: "Algeria / Ligue 1",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:1015",
    competitionName: "Indonesia / Super League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12199513",
    competitionName: "Italian Serie C",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "11687921",
    competitionName: "Mexican Liga MX Femenil",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:26974",
    competitionName: "Iraq / Stars League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "10932509",
    competitionName: "English Premier League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "11428175",
    competitionName: "Turkish Super Cup",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12444373",
    competitionName: "Egyptian League Cup",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:1",
    competitionId: "sr:tournament:727",
    competitionName: "Israel / National League",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "81",
    competitionName: "Italian Serie A",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "1",
    competitionId: "12247754",
    competitionName: "Elite Friendlies",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776378",
    competitionName: "WTA Auckland 2026",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:13131",
    competitionName: "Challenger / ATP Challenger Bengaluru, India Men Singles",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776897",
    competitionName: "Bangalore Challenger 2026",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776599",
    competitionName: "Nonthaburi Challenger 2026",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:41646",
    competitionName: "WTA 125K / WTA 125K Canberra, Australia Women Doubles",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776617",
    competitionName: "ATP Hong Kong 2026",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:45391",
    competitionName: "UTR Men / UTR Olomouc M01",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:50156",
    competitionName: "UTR Women / UTR PTT Stirling Women 01",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12546216",
    competitionName: "United Cup",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "vti:tournament:23457",
    competitionName: "Virtual Tennis In-Play / Virtual Tennis In-Play",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:37077",
    competitionName:
      "Challenger / ATP Challenger Nonthaburi, Thailand Men Singles",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776346",
    competitionName: "WTA Brisbane 2026",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:41218",
    competitionName: "ATP / ATP Hong Kong, Hong Kong Men Singles",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:50150",
    competitionName: "UTR Men / UTR PTT Stirling Men 01",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776723",
    competitionName: "Noumea Challenger 2026",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:3223",
    competitionName:
      "Challenger / ATP Challenger Noumea, New Caledonia Men Doubles",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:38341",
    competitionName: "United Cup / United Cup",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:3221",
    competitionName:
      "Challenger / ATP Challenger Noumea, New Caledonia Men Singles",
    enabled: true,
  },
  {
    providerId: "BetFair",
    sportId: "2",
    competitionId: "12776923",
    competitionName: "Nottingham Challenger 2026",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:50152",
    competitionName: "UTR Men / UTR PTT Wagga Wagga Men 01",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:6497",
    competitionName: "WTA / WTA Auckland, New Zealand Women Singles",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:5167",
    competitionName:
      "Challenger / ATP Challenger Nottingham, Great Britain Men Singles",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:6491",
    competitionName: "WTA / WTA Brisbane, Australia Women Singles",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:48018",
    competitionName: "UTR Men / UTR PTT Athens Men 01",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:47562",
    competitionName: "UTR Women / UTR PTT Krakow Women 01",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:5",
    competitionId: "sr:tournament:41220",
    competitionName: "ATP / ATP Hong Kong, Hong Kong Men Doubles",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:26882",
    competitionName: "Super League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:49222",
    competitionName: "Qatar / QBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1948",
    competitionName: "Romania / Liga Nationala",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:235",
    competitionName: "Liga ABA",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:49007",
    competitionName: "Saudi Arabia / SBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:277",
    competitionName: "Sweden / SBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:132",
    competitionName: "USA / NBA",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:48014",
    competitionName: "Pro B",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1566",
    competitionName: "China / CBA",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1524",
    competitionName: "Australia / NBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:754",
    competitionName: "Serbia / KLS",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1540",
    competitionName: "Republic of Korea / KBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:36147",
    competitionName: "International / WBBL, Women",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:30580",
    competitionName: "Lebanon / First Division",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:35430",
    competitionName: "Turkiye / TBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:26696",
    competitionName: "International / Estonian-Latvian League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:47437",
    competitionName: "China / NBL",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:20154",
    competitionName: "Greece / Elite League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:38919",
    competitionName: "Turkiye / TB2L",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:262",
    competitionName: "Italy / Serie A",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1410",
    competitionName: "Slovakia / Extraliga",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:41774",
    competitionName: "International / WASL Gulf League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1438",
    competitionName: "International / United League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:1516",
    competitionName: "Japan / B2 League",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:14588",
    competitionName: "Cyprus / Division A",
    enabled: true,
  },
  {
    providerId: "SportRadar",
    sportId: "sr:sport:2",
    competitionId: "sr:tournament:14985",
    competitionName: "Italy / Cup, Women",
    enabled: true,
  },

  {
    openDate: "2026-01-05T07:14:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "AU_Nowra",
    competitionName: "AU_Nowra",
    eventId: "35114147",
    eventName: "Nowra (AUS) 5th Jan",
    marketId: "1.252337385",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252337385",
          marketName: "R8 365m Gr5",
          marketTime: 1767609540000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252337390",
          marketName: "R9 520m Gr5",
          marketTime: 1767610440000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252337395",
          marketName: "R10 365m Gr5",
          marketTime: 1767611400000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252337400",
          marketName: "R11 365m Gr2/3",
          marketTime: 1767612300000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T07:28:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "AU_Angle Park",
    competitionName: "AU_Angle Park",
    eventId: "35114193",
    eventName: "Angle Park (AUS) 5th Jan",
    marketId: "1.252338632",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252338632",
          marketName: "R11 530m Gr6",
          marketTime: 1767610560000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338637",
          marketName: "R12 530m Gr4/5",
          marketTime: 1767611520000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T07:37:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "AU_Shepparton",
    competitionName: "AU_Shepparton",
    eventId: "35114186",
    eventName: "Shepparton (AUS) 5th Jan",
    marketId: "1.252338211",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252338211",
          marketName: "R10 450m Vets",
          marketTime: 1767609720000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338216",
          marketName: "R11 390m FFA",
          marketTime: 1767610980000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338221",
          marketName: "R12 390m Gr5",
          marketTime: 1767612060000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338226",
          marketName: "R13 390m Gr5",
          marketTime: 1767613260000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338231",
          marketName: "R14 390m Gr5",
          marketTime: 1767614220000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T08:25:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "AU_Q Straight",
    competitionName: "AU_Q Straight",
    eventId: "35114192",
    eventName: "Q Straight (AUS) 5th Jan",
    marketId: "1.252338547",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252338547",
          marketName: "R8 300m Gr5",
          marketTime: 1767610080000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338552",
          marketName: "R9 300m Gr5",
          marketTime: 1767611340000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338557",
          marketName: "R10 300m Gr5",
          marketTime: 1767612420000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338562",
          marketName: "R11 300m Gr5",
          marketTime: 1767613740000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338567",
          marketName: "R12 300m Gr5",
          marketTime: 1767614820000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338572",
          marketName: "R13 300m Gr5",
          marketTime: 1767615840000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338577",
          marketName: "R14 300m Gr5",
          marketTime: 1767616740000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T08:38:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "AU_Launceston",
    competitionName: "AU_Launceston",
    eventId: "35114338",
    eventName: "Launceston (AUS) 5th Jan",
    marketId: "1.252341963",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      enableMatchOdds: false,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T10:03:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "AU_Mandurah",
    competitionName: "AU_Mandurah",
    eventId: "35114194",
    eventName: "Mandurah (AUS) 5th Jan",
    marketId: "1.252338652",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252338652",
          marketName: "R3 300m Nvce",
          marketTime: 1767609900000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338657",
          marketName: "R4 300m Gr6",
          marketTime: 1767611160000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338662",
          marketName: "R5 400m Gr5/6",
          marketTime: 1767612240000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338667",
          marketName: "R6 300m Gr4/5",
          marketTime: 1767613560000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338672",
          marketName: "R7 488m Gr5/6",
          marketTime: 1767614640000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338677",
          marketName: "R8 300m Gr6",
          marketTime: 1767615540000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338682",
          marketName: "R9 300m Gr5",
          marketTime: 1767616500000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338687",
          marketName: "R10 300m Gr5/6",
          marketTime: 1767617460000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252338692",
          marketName: "R11 400m Nvce",
          marketTime: 1767618360000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T10:32:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "GB_Harlow",
    competitionName: "GB_Harlow",
    eventId: "35115366",
    eventName: "Harlow 5th Jan",
    marketId: "1.252352302",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252352302",
          marketName: "D5 238m",
          marketTime: 1767610080000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352304",
          marketName: "A7 415m",
          marketTime: 1767611040000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352306",
          marketName: "D4 238m",
          marketTime: 1767612060000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352308",
          marketName: "A6 415m",
          marketTime: 1767613080000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352310",
          marketName: "D5 238m",
          marketTime: 1767614040000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352312",
          marketName: "A5 415m",
          marketTime: 1767615120000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352314",
          marketName: "D3 238m",
          marketTime: 1767616140000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352316",
          marketName: "A7 415m",
          marketTime: 1767617160000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352318",
          marketName: "D5 238m",
          marketTime: 1767618180000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352320",
          marketName: "D4 238m",
          marketTime: 1767619140000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353047",
          marketName: "D5 238m",
          marketTime: 1767636660000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353049",
          marketName: "A6 415m",
          marketTime: 1767637740000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353051",
          marketName: "D5 238m",
          marketTime: 1767638760000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353053",
          marketName: "A5 415m",
          marketTime: 1767639840000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353055",
          marketName: "D4 238m",
          marketTime: 1767641040000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353057",
          marketName: "D5 238m",
          marketTime: 1767642120000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353059",
          marketName: "A7 415m",
          marketTime: 1767643080000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353061",
          marketName: "D3 238m",
          marketTime: 1767644160000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353063",
          marketName: "A7 415m",
          marketTime: 1767645240000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252353065",
          marketName: "D5 238m",
          marketTime: 1767646320000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    openDate: "2026-01-05T11:09:00.000+00:00",
    sportId: "4339",
    sportName: "Greyhound Racing",
    competitionId: "GB_Romford",
    competitionName: "GB_Romford",
    eventId: "35115348",
    eventName: "Romford 5th Jan",
    marketId: "1.252352148",
    status: "UPCOMING",
    providerName: "BetFair",
    markets: {
      matchOddsProvider: "BetFair",
      matchOddsBaseUrl: "https://feed.ogpanel.vip/odds-feed",
      matchOddsTopic: "/topic/betfair_match_odds_update",
      matchOdds: [
        {
          marketId: "1.252352148",
          marketName: "A1 400m",
          marketTime: 1767611340000,
          marketType: "MATCH_ODDS",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352150",
          marketName: "A7 400m",
          marketTime: 1767612420000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352152",
          marketName: "A12 400m",
          marketTime: 1767613380000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352154",
          marketName: "A6 400m",
          marketTime: 1767614460000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352156",
          marketName: "A10 400m",
          marketTime: 1767615480000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352158",
          marketName: "S3 575m",
          marketTime: 1767616440000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352160",
          marketName: "A9 400m",
          marketTime: 1767617460000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352162",
          marketName: "A7 400m",
          marketTime: 1767618480000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352164",
          marketName: "A4 400m",
          marketTime: 1767619560000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352166",
          marketName: "A9 400m",
          marketTime: 1767620520000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352168",
          marketName: "A12 400m",
          marketTime: 1767621540000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
        {
          marketId: "1.252352170",
          marketName: "A11 400m",
          marketTime: 1767622440000,
          marketType: "WIN",
          status: "OPEN",
          commissionEnabled: false,
          suspended: false,
          disabled: false,
          limits: {
            minBetValue: 0,
            maxBetValue: 0,
            oddsLimit: 0,
          },
        },
      ],
      enableMatchOdds: true,
      enableBookmaker: false,
      enableFancy: false,
      enablePremium: false,
      fancySuspended: false,
      fancyDisabled: false,
    },
    enabled: true,
    premiumEnabled: false,
    winnerMarketEnabled: false,
    forcedInplay: false,
    virtualEvent: false,
    favorite: false,
  },
  {
    providerId: "RX",
    sportId: "99990",
    competitionId: "999999993",
    competitionName: "Binary",
    enabled: true,
  },
];
